from django.urls import path, include
from utilities.urls import get_model_urls
from .views import (
    ServiceAttachmentDeleteView,
    ServiceAttachmentEditView,
    ServiceRelatedObjectsView,
)
from .forms import (
    ServiceRelatedDevicesForm,
    ServiceRelatedInterfacesForm,
    ServiceRelatedCablesForm,
    ServiceRelatedVLANsForm,
    ServiceRelatedPrefixesForm,
    ServiceRelatedVRFsForm,
    ServiceRelatedASNsForm,
    ServiceRelatedRouteTargetsForm,
    ServiceRelatedL2VPNsForm,
    ServiceRelatedTunnelsForm,
    ServiceRelatedVirtualMachinesForm,
)

urlpatterns = [
    path('',
         include(get_model_urls('netbox_services', 'service', detail=False))
         ),
    path('<int:pk>/',
         include(get_model_urls('netbox_services', 'service', detail=True))
         ),
    path('<int:pk>/attachments/add/',
         ServiceAttachmentEditView.as_view(),
         name='service_attachment_add',
         ),
    path('<int:pk>/attachments/<int:attachment_pk>/delete/',
         ServiceAttachmentDeleteView.as_view(),
         name='service_attachment_delete',
         ),
    path('<int:pk>/relate/devices/',
         ServiceRelatedObjectsView.as_view(form=ServiceRelatedDevicesForm),
         name='relate_devices',
         ),
    path('<int:pk>/relate/interfaces/',
         ServiceRelatedObjectsView.as_view(form=ServiceRelatedInterfacesForm),
         name='relate_interfaces',
         ),
    path('<int:pk>/relate/cables/',
         ServiceRelatedObjectsView.as_view(form=ServiceRelatedCablesForm),
         name='relate_cables',
         ),
    path('<int:pk>/relate/vlans/',
         ServiceRelatedObjectsView.as_view(form=ServiceRelatedVLANsForm),
         name='relate_vlans',
         ),
    path('<int:pk>/relate/prefixes/',
         ServiceRelatedObjectsView.as_view(form=ServiceRelatedPrefixesForm),
         name='relate_prefixes',
         ),
    path('<int:pk>/relate/vrfs/',
         ServiceRelatedObjectsView.as_view(form=ServiceRelatedVRFsForm),
         name='relate_vrfs',
         ),
    path('<int:pk>/relate/asns/',
         ServiceRelatedObjectsView.as_view(form=ServiceRelatedASNsForm),
         name='relate_asns',
         ),
    path('<int:pk>/relate/route_targets/',
         ServiceRelatedObjectsView.as_view(form=ServiceRelatedRouteTargetsForm),
         name='relate_route_targets',
         ),
    path('<int:pk>/relate/l2vpns/',
         ServiceRelatedObjectsView.as_view(form=ServiceRelatedL2VPNsForm),
         name='relate_l2vpns',
         ),
    path('<int:pk>/relate/tunnels/',
         ServiceRelatedObjectsView.as_view(form=ServiceRelatedTunnelsForm),
         name='relate_tunnels',
         ),
    path('<int:pk>/relate/virtual_machines/',
         ServiceRelatedObjectsView.as_view(form=ServiceRelatedVirtualMachinesForm),
         name='relate_virtual_machines',
         ),
]
