# Generated by Django 6.0.8 on 2026-08-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
