# Generated by Django 6.0.8 on 2026-08-21 14:06

import django.db.models.deletion
import netbox.models.deletion
import netbox_services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_services", "0002_add_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="contract_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="contract_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="decommissioned",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="installed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="order_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="planned_activation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="requested_disconnect",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ServiceAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "file",
                    models.FileField(
                        upload_to=netbox_services.models.service_attachment_upload
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="netbox_services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service attachment",
                "verbose_name_plural": "Service attachments",
                "ordering": ("name", "pk"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
